[workspace]
authors = ["nkfreeman <nkfreeman@cba.ua.edu>"]
channels = ["conda-forge"]
name = "dewey_demo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
pyarrow = ">=22.0.0,<23"
polars = ">=1.35.1,<2"
ipython = ">=9.7.0,<10"
ipywidgets = ">=8.1.8,<9"
tqdm = ">=4.67.1,<5"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
duckdb = ">=1.4.1,<2"
marimo = ">=0.17.7,<0.18"
